//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimLettersWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physician
    {
        public int Id_Facility { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public int Id_Letter_Type { get; set; }
        public int Id { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Letter_Type Letter_Type { get; set; }
    }
}
